### PR TITLE
⚠️Urgent Update 

### PR DESCRIPTION
**Pull request by tierracero**
Recent update to swift-nio ByteBuffer.writeString requires explicit use on \r\n for new lines, ignores triple quotes.
@Joannis

### CODE REVIEW

**Comment by petrpavlik** [comment]
Just tried to send a multiline plaintext email with current implementation `"Llllll\nddddd\nuuuuuu"` using swift-nio 2.63 (the latest release), and the new lines look just fine in apple mail app?
Screenshot 2024-02-16 at 0 52 09

`.alternative` also seems to work fine as it is?

**Comment by tierracero** [comment]
@petrpavlik  what Swift version are you  using on your server. its also posible that  its not swift-nio,  I suppose since its  been modified in recent days.  Could you send a test mail to an outlook account ??

IMG_4004

IMG_4005

this is the same code  the difference is  the patch

image

WHERE ITEMS is 

var items: [MailContentConvertible] = []

image

How did you test out Mail.Content.alternative?

**Comment by petrpavlik** [comment]
Will try an outlook email, make sense since `\r\n` is a new line on windows, and will let you know.

**Comment by petrpavlik** [comment]
Ok, I've tried from gmail to outlook and the other way around. Everything seems to work just fine. Will post here the API / swift version later today.

**Comment by petrpavlik** [comment]
I'm using dockerized Swift 5.9.2 on ubuntu22.04. Recently forked this repo to add support for custom headers, so that's what I'm using https://github.com/Joannis/SMTPKitten/pull/13

I'm running a vapor backend, so I have SMTPKitten integrated using https://github.com/petrpavlik/VaporSMTPKit

```swift
let email = Mail(
                from: .init(name: account.senderName, email: account.emailAlias ?? account.email),
                to: [
                    MailUser(name: nil, email: data.recipientEmail)
                ],
                subject: subject,
                content: draft.bodyType == .plaintext ? .plain(body) : .alternative(plaintextBody, html: body)
            )
            
            try await req.application.sendMail(email, withCredentials: credentials)
```

**Comment by tierracero** [comment]
@petrpavlik  we are using the same distribution and  swim version... 

 but its odd bc  I have an other server (a very simple server that controls my back ups)

witch has no fancy code impacted with the same issue 

image

in the next image  I join an array of string  with "\n"

image

and next, es the script  sending email
 
image

an these are the libs I use, this project is nothing  fancy 

image

I really don't know   what is the difference... ¿any ideas, what could we test?

**Comment by tierracero** [comment]
@petrpavlik  well im using the same distro and swift verision I believe  I even have a second server  that only does back ups  its a very simple project thou its also impacted by the same issue 

Welcome to Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-171-generic x86_64)

Swift version 5.9.2 (swift-5.9.2-RELEASE)
Target: x86_64-unknown-linux-gnu

image


let **listOfBackups**: [String] = [ "bk1", "bk2" , "bk3" ... ]

let body =  **listOfBackups**.joined(separator: "\n")


image

image

and that is the result... as you can see... im really not doing anything out of the ordinary... 
my server defaultt text encoding utf8 witch I think is very much standard...

¿Any suggestions?

bc its not one sole project being impacted its two... but its also odd that your not being impacted. I have no idea what could be different.

**Comment by tierracero** [comment]
@petrpavlik 

 can you please use this exact email format 


    let mail = Mail(
        from: .init(name: fromName, email: fromEmail),
        to: [.init(name: "Your Name", email: "your@mail.com")],
        subject: subject
    ) {
        Mail.Content.plain(body)
        Mail.Content.plain(
            "\r\n\r\n" +
            "FILE: \(file)\r\n" +
            "LINE: \(line)\r\n" +
            "FUNC: \(function)"
        )
    }

 just to test in maybe this is the method producing the error  please

**Comment by tierracero** [comment]
@petrpavlik  also who is you mail provider  im using cPanel...

**Comment by petrpavlik** [comment]
@tierracero I've tried to send an email using a google workspace and an outlook email account so far. Will try that snippet you posted later.

**Comment by tierracero** [comment]
@Joannis i believe you have approved this request, col you please also merge it :)

**Comment by Joannis** [comment]
@tierracero I didn't approve it, because I don't see and can't reproduce the issue.

**Comment by Joannis** [comment]
@tierracero if you're able, could you share what SMTP server you're using?

**Comment by tierracero** [comment]
all i see then the only think I think  could be is cPanel issue …  if you don’t mind me asking what SMTP user  do you use ??

**Comment by Joannis** [comment]
I have a mailserver by transip.nl, but I've also used Microsoft Exchange at times.

**Comment by Joannis** [comment]
@tierracero that being said, I don't think it's necessarily an issue with cPanel, it could be a small bug in SMTPKitten that only affects your scenario. But I don't have a lot of info to go on

**Comment by tierracero** [comment]
@Joannis  ill send the info  and  some credencial  by private message  :)

**Pull request closed without merging**
